name: "Master Build, Test, Customize & Deploy"

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: gchq/CyberChef
        ref: master

    - name: Set node version
      uses: actions/setup-node@v1
      with:
        node-version: '17.x'

    - name: Install
      run: |
        npm install
        npm run setheapsize
    - name: Lint
      run: npx grunt lint

    - name: Unit Tests
      run: |
        npm test
        npx grunt testnodeconsumer

    - name: Production Build
      if: success()
      run: npx grunt prod

    - name: Generate sitemap
      run: npx grunt exec:sitemap

    #- name: UI Tests
    #  if: success()
    #  run: xvfb-run --server-args="-screen 0 1200x800x24" npx grunt testui

    - name: Prepare for GitHub Pages
      if: success()
      run: npx grunt copy:ghPages

    # custom
    - name: Customize
      if: success()
      working-directory: ./build/prod
      env:
        CDN_PREFIX: "https://cdn.jsdelivr.net/gh/cubarco/CyberChef-forked@gh-pages"
      run: |
        rm CyberChef*.zip
        rm sitemap.xml
        sed -i "/Begin Google/,/End Google/d" index.html
        #sed -i "s~assets/main.css~${CDN_PREFIX}/assets/main.css~" index.html
        #sed -i "s~assets/main.js~${CDN_PREFIX}/assets/main.js~" index.html
        #sed -i "s~self.docURL=r.data~self.docURL=\"${CDN_PREFIX}\"~" assets/main.js

    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: ./build/prod
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
