name: "Fork sync with upstream"

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync main with upstream latest

    steps:
    # Step 1: run a standard checkout action, provided by github
    - name: Checkout current branch
      uses: actions/checkout@v2
      with:
        ref: upstream-master

    # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
    - name: Pull (Fast-Forward) upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.1
      env:
          GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN }}
      with:
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        target_sync_branch: upstream-master
        upstream_sync_repo: gchq/CyberChef
        upstream_sync_branch: master

    - name: Notify build workflow.
      if: ${{ steps.sync.outputs.has_new_commits == 'true' }}
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: "Master Build, Test, Customize & Deploy"
        token: ${{ secrets.PERSONAL_TOKEN }}
